apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    component: kube-proxy
    tier: node
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        component: kube-proxy
        tier: node
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - command:
        - /hyperkube
        - proxy
        - --kubeconfig=/var/lib/kubelet/kubeconfig
        - --cluster-cidr=172.31.0.0/16
        - --feature-gates=ExperimentalCriticalPodAnnotation=true
        image: k8s.gcr.io/hyperkube-amd64:v1.10.12
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /etc/kubernetes
          name: etc-kubernetes
          readOnly: true
        - mountPath: /var/lib/kubelet/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /run/xtables.lock
          name: iptableslock
      hostNetwork: true
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: ssl-certs-host
      - hostPath:
          path: /var/lib/kubelet/kubeconfig
        name: kubeconfig
      - hostPath:
          path: /etc/kubernetes
        name: etc-kubernetes
      - hostPath:
          path: /run/xtables.lock
        name: iptableslock
      nodeSelector:
        beta.kubernetes.io/os: linux